made XDG compatible, dmenu scripts are customized to follow whole theme more closely, qtile bar margin is made to such that dmenu is adjusted accordingly

diff --git a/.local/bin/scripts/ifinstalled b/.local/bin/scripts/ifinstalled
--- a/.local/bin/scripts/ifinstalled
+++ b/.local/bin/scripts/ifinstalled
@@ -1,5 +1,25 @@
 #!/bin/sh
 
+while getopts ":q:" opt; do
+	case $opt in
+		q)
+			for x in "$@"; do
+				if ! which "$x" >/dev/null 2>&1 && ! pacman -Qq "$x" >/dev/null 2>&1; then
+					exit 1 ;
+				fi
+			done
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+		:)
+			echo "Option -$OPTARG requires an argument." >&2
+			exit 1
+			;;
+	esac
+done
+
 for x in "$@"; do
 	if ! which "$x" >/dev/null 2>&1 && ! pacman -Qq "$x" >/dev/null 2>&1; then
  		notify-send "📦 $x" "must be installed for this function." && exit 1 ;
